# Generated by Django 3.0.5 on 2020-05-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_auto_20200512_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
