# Generated by Django 3.0.5 on 2020-05-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200426_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
