# Generated by Django 3.0.5 on 2020-05-12 22:08

from django.db import migrations


def copy_person_to_entity(apps, scheme_editor):
    from django.db.models.expressions import F

    Tweet = apps.get_model('news', 'Tweet')
    Person = apps.get_model('entity', 'Person')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    person_ct = ContentType.objects.get_for_model(Person)
    n = Tweet.objects.filter(object_id=None).update(content_type=person_ct, object_id=F('person_id'))
    print('Copied person to entity for [%s] Tweets' % n)


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200512_2205'),
    ]

    operations = [
        migrations.RunPython(copy_person_to_entity, migrations.RunPython.noop)
    ]
