# Generated by Django 3.0.5 on 2020-05-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200523_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
