# Generated by Django 3.0.5 on 2020-04-25 19:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_person_twitter_handle'),
        ('news', '0002_article_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_on',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('tweet_id', models.BigIntegerField()),
                ('tweet', models.TextField()),
                ('published_on', models.DateTimeField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Person')),
            ],
            options={
                'ordering': ['-created_on', 'updated_on'],
                'get_latest_by': 'created_on',
                'abstract': False,
            },
        ),
    ]
