# Generated by Django 3.0.5 on 2020-05-12 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('news', '0010_auto_20200512_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='person',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
