# Generated by Django 3.0.5 on 2020-06-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20200523_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsIndex',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('author', models.TextField()),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('query', models.TextField()),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'es_articles',
                'managed': False,
            },
        ),
    ]
