# Generated by Django 3.0.7 on 2020-07-11 21:10

from django.db import migrations, models
import mnemonic.news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_newsindex'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='feed',
            managers=[
                ('objects', mnemonic.news.models.CachedManager()),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
