# Generated by Django 3.0.7 on 2020-07-16 18:49

from django.db import migrations
import mnemonic.news.utils.queryset_utils


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20200711_2110'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newssource',
            managers=[
                ('objects', mnemonic.news.utils.queryset_utils.CachedManager()),
            ],
        ),
    ]
