# Generated by Django 3.0.7 on 2021-01-15 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('news', '0016_auto_20200716_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
