# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-25 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('political_party', 'Political Party')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('from_entity_object_id', models.PositiveIntegerField()),
                ('to_entity_object_id', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('is_party_member_of', 'is party member of')], max_length=100)),
                ('from_entity_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_entity_content_type', to='contenttypes.ContentType')),
                ('to_entity_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_entity_content_type', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-created_on', 'updated_on'],
                'abstract': False,
                'get_latest_by': 'created_on',
            },
        ),
    ]
