# Generated by Django 3.0.5 on 2020-04-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='twitter_handle',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
